sudo: required
services:
  - docker
before_install:
  - docker build -t dmitrybunin/docker-react -f Dockerfile.dev .

script:
  # -- --coverage makes 'npm run test' exit (with status 0) once the test run is finished
  # istead of waiting for user input
  - docker run -e CI=true dmitrybunin/docker-react npm run test -- --coverage 